import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  Cpu,
  Boxes,
  CalendarRange,
  ScrollText,
  ShieldCheck,
  Layers,
  CirclePlay,
  CircleStop,
  Timer,
  Hourglass,
  Boxes as ClusterIcon,
  CloudCog,
  FileKey,
  BadgeCheck,
  CircleX,
  CircleAlert,
  RefreshCcw,
  Trash2,
  PlusCircle,
  PenLine,
  KeyRound,
  UsersRound,
  UserRoundPlus,
  ScanSearch,
  ListFilter,
  Loader2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Copy,
  FileJson,
  FileUp,
  FolderOpen,
  FolderKanban,
  Workflow,
  Activity,
  Fingerprint,
  Globe2,
  Database,
  Bolt,
  SlidersHorizontal,
  Sparkles,
  Command,
  BellRing,
  MessageSquare,
  Mail,
  Webhook,
  Settings2,
  LogOut,
  TriangleAlert,
  ServerCog,
  Rocket,
  FlaskConical,
  Info,
  Save,
  X,
  MoonStar,
  SunMedium,
  Phone,
  UserRound,
  PiggyBank,
  TrendingDown,
  Radio,
  SendHorizonal,
} from 'lucide-react';

/** Thin modern stroke — visible in light and dark mode */
export const ICON_STROKE = 1.75;

export {
  LayoutDashboard,
  Cpu,
  Boxes,
  CalendarRange,
  ScrollText,
  ShieldCheck,
  Layers,
  CirclePlay,
  CircleStop,
  Timer,
  Hourglass,
  ClusterIcon,
  CloudCog,
  FileKey,
  BadgeCheck,
  CircleX,
  CircleAlert,
  RefreshCcw,
  Trash2,
  PlusCircle,
  PenLine,
  KeyRound,
  UsersRound,
  UserRoundPlus,
  ScanSearch,
  ListFilter,
  Loader2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Copy,
  FileJson,
  FileUp,
  FolderOpen,
  FolderKanban,
  Workflow,
  Activity,
  Fingerprint,
  Globe2,
  Database,
  Bolt,
  SlidersHorizontal,
  Sparkles,
  Command,
  BellRing,
  MessageSquare,
  Mail,
  Webhook,
  Settings2,
  LogOut,
  TriangleAlert,
  ServerCog,
  Rocket,
  FlaskConical,
  Info,
  Save,
  X,
  MoonStar,
  SunMedium,
  Phone,
  UserRound,
  PiggyBank,
  TrendingDown,
  Radio,
  SendHorizonal,
};

/** Semantic aliases used across the app */
export const Icons = {
  pages: {
    dashboard: LayoutDashboard,
    infrastructure: Cpu,
    clusters: Boxes,
    schedules: CalendarRange,
    activity: ScrollText,
    admin: ShieldCheck,
    liveSchedules: Activity,
    resourceAudit: Fingerprint,
    security: ShieldCheck,
    alerts: BellRing,
    contact: UsersRound,
  },
  dashboard: {
    apps: Layers,
    running: CirclePlay,
    stopped: CircleStop,
    clusters: ClusterIcon,
    scheduled: CalendarRange,
    runningHours: Timer,
    stoppedHours: Hourglass,
    schedules: CalendarRange,
  },
  status: {
    success: BadgeCheck,
    error: CircleX,
    warning: TriangleAlert,
    info: Info,
  },
  actions: {
    add: PlusCircle,
    edit: PenLine,
    delete: Trash2,
    refresh: RefreshCcw,
    search: ScanSearch,
    filter: ListFilter,
    save: Save,
    test: Bolt,
    start: CirclePlay,
    stop: CircleStop,
  },
} as const satisfies Record<string, Record<string, LucideIcon>>;
