import { formatTimestampIST } from './utils';
import type { SecurityToolDefinition } from './security-tools';
import type { SecurityResourceView } from './security-service';
import {
  buildReportDocumentTitle,
  buildReportHeaderHtml,
  categoryReportLabel,
  categoryReportSubtitle,
  reportPageStyles,
} from './security-report-html';
import {
  resolveSecretsRemediation,
  type SecretsRemediation,
} from './security/secrets-remediation';
import {
  buildFindingSourceUrls,
  type RepoSourceContext,
} from './security/repo-source-url';

export interface SecurityReportContext {
  resource: SecurityResourceView | null;
  tool: SecurityToolDefinition;
  title: string;
  summary: string;
  severityCounts?: { high: number; medium: number; low: number };
  scaDependencies?: ScaDependencyRow[];
  secretsFindings?: SecretsFindingRow[];
}

export interface SecretsFindingRow {
  id?: string;
  severity: string;
  rule: string;
  location: string;
  message: string;
  urls?: string[];
  recommendation?: string;
  remediationSteps?: string[];
  remediationCommands?: string[];
}

export function buildSecurityReportHtml(ctx: SecurityReportContext): string {
  if (ctx.tool.category === 'sast') {
    return buildSastReportHtml(ctx);
  }
  if (ctx.tool.category === 'sca') {
    return buildScaReportHtml(ctx);
  }
  if (ctx.tool.category === 'secrets') {
    return buildSecretsReportHtml(ctx);
  }

  const resourceName = ctx.resource?.name ?? 'Target';
  const target =
    ctx.resource?.type === 'repository'
      ? `${ctx.resource.repoUrl ?? '—'}${ctx.resource.defaultBranch ? ` (${ctx.resource.defaultBranch})` : ''}`
      : ctx.resource?.targetUrl ?? '—';
  const generatedAt = formatTimestampIST(new Date().toISOString());
  const docTitle = buildReportDocumentTitle(ctx.tool.category, ctx.tool.name, resourceName);
  const targetLabel = ctx.resource?.type === 'target_url' ? 'URL Target' : 'Repository';

  const findings = sampleFindings(ctx.tool.id);

  const rows = findings
    .map(
      (row) => `
      <tr>
        <td>${escapeHtml(row.severity)}</td>
        <td>${escapeHtml(row.rule)}</td>
        <td><code>${escapeHtml(row.location)}</code></td>
        <td>${escapeHtml(row.message)}</td>
      </tr>`
    )
    .join('');

  const header = buildReportHeaderHtml({
    categoryLabel: categoryReportLabel(ctx.tool.category),
    toolName: escapeHtml(ctx.tool.name),
    resourceName: escapeHtml(resourceName),
    subtitle: categoryReportSubtitle(ctx.tool.category),
    generatedAt: escapeHtml(generatedAt),
    targetLabel,
    targetValue: escapeHtml(target),
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(docTitle)}</title>
  <style>${reportPageStyles()}</style>
</head>
<body>
  <div class="page">
    ${header}
    <div class="report-body">
      <div class="summary-box">${escapeHtml(ctx.summary)}</div>
      <h2>Findings</h2>
      <table class="findings-table">
        <thead>
          <tr>
            <th>Severity</th>
            <th>Rule</th>
            <th>Location</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
    <p class="report-footer">SecureNexus Security · Generated by ${escapeHtml(ctx.tool.name)}</p>
  </div>
</body>
</html>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeHtmlAttr(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;');
}

function parseLocationParts(location: string): { file: string; line?: number } {
  const colon = location.lastIndexOf(':');
  if (colon <= 0) return { file: location };
  const tail = location.slice(colon + 1);
  if (!/^\d+$/.test(tail)) return { file: location };
  return { file: location.slice(0, colon), line: Number(tail) };
}

function enrichSecretsFindingUrls(
  findings: SecretsFindingRow[],
  resource: SecurityResourceView | null
): SecretsFindingRow[] {
  if (!resource?.repoUrl?.trim()) return findings;

  const context: RepoSourceContext = {
    repoUrl: resource.repoUrl,
    defaultBranch: resource.defaultBranch,
  };

  return findings.map((row) => {
    if (row.urls?.length) return row;
    const { file, line } = parseLocationParts(row.location);
    const urls = buildFindingSourceUrls(context, {
      file,
      startLine: line,
      endLine: line,
    });
    return urls.length ? { ...row, urls } : row;
  });
}

interface SastFindingRow {
  severity: string;
  rule: string;
  location: string;
  message: string;
}

function bucketFinding(finding: SastFindingRow): 'Critical' | 'High' | 'Medium' | 'Low' | 'Warning' {
  const sev = finding.severity.toLowerCase();
  if (sev === 'critical') return 'Critical';
  if (sev === 'high') return 'High';
  if (sev === 'medium') return 'Medium';
  if (sev === 'warning') return 'Warning';
  return 'Low';
}

function buildSastObservations(repoName: string, findings: SastFindingRow[]): string[] {
  if (!findings.length) return ['No SAST findings detected in this scan.'];

  const observations: string[] = [];
  const sql = findings.filter((f) => /sql/i.test(f.rule) || /sql/i.test(f.message));
  const secrets = findings.filter((f) =>
    /secret|credential|password|api-key/i.test(`${f.rule}${f.message}`)
  );
  const high = findings.filter((f) => /high|critical/i.test(f.severity));

  if (sql.length) {
    observations.push(
      `SQL injection or unsafe query patterns found in ${repoName} (${sql.length} finding${sql.length === 1 ? '' : 's'}).`
    );
  }
  if (secrets.length) {
    observations.push(
      `Hardcoded secrets or credential patterns detected in ${repoName} (${secrets.length} finding${secrets.length === 1 ? '' : 's'}).`
    );
  }
  if (high.length) {
    observations.push(
      `${high.length} high-severity issue${high.length === 1 ? '' : 's'} in ${repoName} require immediate remediation.`
    );
  }
  if (observations.length < 3) {
    observations.push(
      `Review ${findings.length} finding${findings.length === 1 ? '' : 's'} in the detailed SAST summary table below.`
    );
  }
  return observations.slice(0, 6);
}

function sampleSecretsFindings(toolId: string): SecretsFindingRow[] {
  const rows = [
    {
      id: 'K-001',
      severity: 'High',
      rule: `${toolId}:aws-access-token`,
      location: 'config/production.env:12',
      message: 'AWS access key detected — match: AKIA…XY',
    },
    {
      id: 'K-002',
      severity: 'High',
      rule: `${toolId}:private-key`,
      location: 'deploy/id_rsa:1',
      message: 'Private key detected — match: ----…--',
    },
    {
      id: 'K-003',
      severity: 'Medium',
      rule: `${toolId}:generic-api-key`,
      location: 'src/lib/client.ts:88',
      message: 'Generic API key pattern detected — match: sk_l…9a',
    },
  ];

  return rows.map((row) => {
    const remediation = resolveSecretsRemediation(row.rule, row.location);
    return {
      ...row,
      recommendation: remediation.summary,
      remediationSteps: remediation.steps,
      remediationCommands: remediation.commands,
    };
  });
}

function buildSecretsUrlCell(urls: string[] | undefined): string {
  if (!urls?.length) return '—';

  const items = urls
    .map(
      (url) =>
        `<li><a href="${escapeHtmlAttr(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(url)}</a></li>`
    )
    .join('');

  return `<ul class="source-url-list">${items}</ul>`;
}

function buildSecretsRemediationCell(row: SecretsFindingRow): string {
  const remediation: SecretsRemediation = row.recommendation
    ? {
        summary: row.recommendation,
        steps: row.remediationSteps ?? [],
        commands: row.remediationCommands ?? [],
      }
    : resolveSecretsRemediation(row.rule, row.location);

  const steps = remediation.steps
    .map((step) => `<li>${escapeHtml(step)}</li>`)
    .join('');
  const commands = remediation.commands.length
    ? `<pre class="remediation-cmd">${remediation.commands.map((cmd) => escapeHtml(cmd)).join('\n')}</pre>`
    : '';

  return `<div class="remediation">
    <p class="remediation-summary">${escapeHtml(remediation.summary)}</p>
    ${steps ? `<ol class="remediation-steps">${steps}</ol>` : ''}
    ${commands}
  </div>`;
}

function buildSecretsObservations(repoName: string, findings: SecretsFindingRow[]): string[] {
  if (!findings.length) return ['No hard-coded secrets detected in this scan.'];

  const observations: string[] = [];
  const high = findings.filter((f) => /high|critical/i.test(f.severity));
  const keys = findings.filter((f) => /private-key|ssh|rsa/i.test(`${f.rule}${f.message}`));
  const cloud = findings.filter((f) => /aws|azure|gcp|github|gitlab|slack|stripe/i.test(`${f.rule}${f.message}`));

  if (high.length) {
    observations.push(
      `${high.length} high-severity secret${high.length === 1 ? '' : 's'} in ${repoName} require immediate rotation and removal from source control.`
    );
  }
  if (cloud.length) {
    observations.push(
      `Cloud or SaaS credentials detected (${cloud.length} finding${cloud.length === 1 ? '' : 's'}) — revoke and rotate affected tokens.`
    );
  }
  if (keys.length) {
    observations.push(
      `Private key material found in ${keys.length} location${keys.length === 1 ? '' : 's'}.`
    );
  }
  observations.push(
    `Review ${findings.length} finding${findings.length === 1 ? '' : 's'} in the secrets summary table below.`
  );
  return observations.slice(0, 6);
}

export function buildSecretsReportHtml(ctx: SecurityReportContext): string {
  const repoName = ctx.resource?.name ?? 'repository';
  const target =
    ctx.resource?.type === 'repository'
      ? `${ctx.resource.repoUrl ?? '—'}${ctx.resource.defaultBranch ? ` (${ctx.resource.defaultBranch})` : ''}`
      : ctx.resource?.targetUrl ?? '—';
  const generatedAt = formatTimestampIST(new Date().toISOString());
  const docTitle = buildReportDocumentTitle('secrets', ctx.tool.name, repoName);

  const findings = enrichSecretsFindingUrls(
    ctx.secretsFindings ?? sampleSecretsFindings(ctx.tool.id),
    ctx.resource
  );
  const counts = { Critical: 0, High: 0, Medium: 0, Low: 0, Warning: 0 };
  for (const row of findings) {
    const bucket = bucketFinding(row);
    counts[bucket] += 1;
  }

  const total = findings.length;
  const criticalHigh = counts.Critical + counts.High;
  const lowInfo = counts.Low + counts.Warning;
  const observations = buildSecretsObservations(repoName, findings);

  const detailRows = findings
    .map(
      (row, index) => `
      <tr>
        <td>${escapeHtml(row.id ?? `K-${String(index + 1).padStart(3, '0')}`)}</td>
        <td>${escapeHtml(row.rule)}</td>
        <td>${escapeHtml(row.severity)}</td>
        <td>${escapeHtml(repoName)}</td>
        <td><code>${escapeHtml(row.location)}</code></td>
        <td>${buildSecretsUrlCell(row.urls)}</td>
        <td>${escapeHtml(row.message)}</td>
        <td>${buildSecretsRemediationCell(row)}</td>
      </tr>`
    )
    .join('');

  const observationItems = observations.map((item) => `<li>${escapeHtml(item)}</li>`).join('');

  const header = buildReportHeaderHtml({
    categoryLabel: 'Secrets',
    toolName: escapeHtml(ctx.tool.name),
    resourceName: escapeHtml(repoName),
    subtitle: categoryReportSubtitle('secrets'),
    generatedAt: escapeHtml(generatedAt),
    targetLabel: 'Repository',
    targetValue: escapeHtml(target),
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(docTitle)}</title>
  <style>${reportPageStyles()}</style>
</head>
<body>
  <div class="page">
    ${header}
    <div class="report-body">
      <h2>Issue Summary</h2>
      <table class="summary-table">
        <thead>
          <tr>
            <th>Total Issues</th>
            <th>Critical / High</th>
            <th>Medium</th>
            <th>Low / Info</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="cell-total">${total}</td>
            <td class="cell-critical-high">${criticalHigh}</td>
            <td class="cell-medium">${counts.Medium}</td>
            <td class="cell-low-info">${lowInfo}</td>
          </tr>
        </tbody>
      </table>

      <h2>Issues by Repository</h2>
      <table>
        <thead>
          <tr>
            <th class="text-left">Repository</th>
            <th class="col-critical">Critical</th>
            <th class="col-high">High</th>
            <th>Medium</th>
            <th>Low</th>
            <th>Warning</th>
            <th>Tool</th>
          </tr>
        </thead>
        <tbody>
          <tr class="row-alt">
            <td class="text-left">${escapeHtml(repoName)}</td>
            <td class="col-critical">${counts.Critical}</td>
            <td class="col-high">${counts.High}</td>
            <td>${counts.Medium}</td>
            <td>${counts.Low}</td>
            <td>${counts.Warning}</td>
            <td>${escapeHtml(ctx.tool.name)}</td>
          </tr>
        </tbody>
      </table>

      <h3>Key Observations</h3>
      <div class="observations">
        <ul>${observationItems}</ul>
      </div>

      <h2>5.1 Secrets Summary Table</h2>
      <table class="detail-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Rule</th>
            <th>Severity</th>
            <th>Repository</th>
            <th>Location</th>
            <th>URL</th>
            <th>Description</th>
            <th>Fix / Remediation</th>
          </tr>
        </thead>
        <tbody>${detailRows || '<tr><td colspan="8" style="text-align:center;padding:24px;">No secrets detected</td></tr>'}</tbody>
      </table>
    </div>
    <p class="report-footer">SecureNexus Security · Generated by ${escapeHtml(ctx.tool.name)}</p>
  </div>
</body>
</html>`;
}

function buildSastReportHtml(ctx: SecurityReportContext): string {
  const repoName = ctx.resource?.name ?? 'repository';
  const target =
    ctx.resource?.type === 'repository'
      ? `${ctx.resource.repoUrl ?? '—'}${ctx.resource.defaultBranch ? ` (${ctx.resource.defaultBranch})` : ''}`
      : ctx.resource?.targetUrl ?? '—';
  const generatedAt = formatTimestampIST(new Date().toISOString());
  const docTitle = buildReportDocumentTitle('sast', ctx.tool.name, repoName);

  const findings = sampleFindings(ctx.tool.id);
  const counts = { Critical: 0, High: 0, Medium: 0, Low: 0, Warning: 0 };
  for (const row of findings) {
    counts[bucketFinding(row)] += 1;
  }

  const total = findings.length;
  const criticalHigh = counts.Critical + counts.High;
  const lowInfo = counts.Low + counts.Warning;
  const observations = buildSastObservations(repoName, findings);

  const detailRows = findings
    .map(
      (row, index) => `
      <tr>
        <td>S-${String(index + 1).padStart(3, '0')}</td>
        <td>${escapeHtml(row.message.split('.')[0] || row.rule)}</td>
        <td>${escapeHtml(row.severity)}</td>
        <td>${escapeHtml(repoName)}</td>
        <td><code>${escapeHtml(row.location)}</code></td>
        <td>—</td>
        <td>—</td>
        <td>${escapeHtml(row.message)}</td>
      </tr>`
    )
    .join('');

  const observationItems = observations.map((item) => `<li>${escapeHtml(item)}</li>`).join('');

  const header = buildReportHeaderHtml({
    categoryLabel: 'SAST',
    toolName: escapeHtml(ctx.tool.name),
    resourceName: escapeHtml(repoName),
    subtitle: categoryReportSubtitle('sast'),
    generatedAt: escapeHtml(generatedAt),
    targetLabel: 'Repository',
    targetValue: escapeHtml(target),
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(docTitle)}</title>
  <style>${reportPageStyles()}</style>
</head>
<body>
  <div class="page">
    ${header}
    <div class="report-body">
      <h2>Issue Summary</h2>
      <table class="summary-table">
        <thead>
          <tr>
            <th>Total Issues</th>
            <th>Critical / High</th>
            <th>Medium</th>
            <th>Low / Info</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="cell-total">${total}</td>
            <td class="cell-critical-high">${criticalHigh}</td>
            <td class="cell-medium">${counts.Medium}</td>
            <td class="cell-low-info">${lowInfo}</td>
          </tr>
        </tbody>
      </table>

      <h2>Issues by Repository</h2>
      <table>
        <thead>
          <tr>
            <th class="text-left">Repository</th>
            <th class="col-critical">Critical</th>
            <th class="col-high">High</th>
            <th>Medium</th>
            <th>Low</th>
            <th>Warning</th>
            <th>Tool</th>
          </tr>
        </thead>
        <tbody>
          <tr class="row-alt">
            <td class="text-left">${escapeHtml(repoName)}</td>
            <td class="col-critical">${counts.Critical}</td>
            <td class="col-high">${counts.High}</td>
            <td>${counts.Medium}</td>
            <td>${counts.Low}</td>
            <td>${counts.Warning}</td>
            <td>${escapeHtml(ctx.tool.name)}</td>
          </tr>
        </tbody>
      </table>

      <h3>Key Observations</h3>
      <div class="observations">
        <ul>${observationItems}</ul>
      </div>

      <h2>3.1 SAST Summary Table</h2>
      <table class="detail-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Vulnerability</th>
            <th>Severity</th>
            <th>Repository</th>
            <th>Location</th>
            <th>CWE</th>
            <th>OWASP</th>
            <th>Recommendation</th>
          </tr>
        </thead>
        <tbody>${detailRows || '<tr><td colspan="8" style="text-align:center;padding:24px;">No findings</td></tr>'}</tbody>
      </table>
    </div>
    <p class="report-footer">SecureNexus Security · Generated by ${escapeHtml(ctx.tool.name)}</p>
  </div>
</body>
</html>`;
}

function scaSeverityClass(severity: string): string {
  const sev = severity.toLowerCase();
  if (sev === 'high' || sev === 'critical') return 'sev-sca-high';
  if (sev === 'moderate' || sev === 'medium') return 'sev-sca-moderate';
  return 'sev-sca-low';
}

export interface ScaDependencyRow {
  id: string;
  package: string;
  currentVersion: string;
  fixVersion: string;
  severity: 'High' | 'Moderate' | 'Low';
  cve: string;
  vulnerability: string;
  action: string;
}

export function sampleScaDependencies(_toolId: string): ScaDependencyRow[] {
  return [
    {
      id: 'D-001',
      package: 'minimatch',
      currentVersion: '3.1.2',
      fixVersion: '3.1.3',
      severity: 'High',
      cve: 'GHSA-3ppc-xxxx',
      vulnerability: 'ReDoS',
      action: 'Upgrade to 3.1.3+',
    },
    {
      id: 'D-002',
      package: 'minimatch',
      currentVersion: '9.0.5',
      fixVersion: '9.0.6',
      severity: 'High',
      cve: 'GHSA-7r86-xxxx',
      vulnerability: 'ReDoS',
      action: 'Upgrade to 9.0.6+',
    },
    {
      id: 'D-003',
      package: 'lodash',
      currentVersion: '4.17.15',
      fixVersion: 'Latest',
      severity: 'Moderate',
      cve: 'GHSA-xxjr-xxxx',
      vulnerability: 'Prototype Pollution',
      action: 'Upgrade to latest',
    },
    {
      id: 'D-004',
      package: 'qs',
      currentVersion: '6.5.3',
      fixVersion: '6.14.1',
      severity: 'High',
      cve: 'GHSA-6rw7-xxxx',
      vulnerability: 'DoS via memory exhaustion',
      action: 'Upgrade to 6.14.1+',
    },
    {
      id: 'D-005',
      package: 'tar',
      currentVersion: '6.2.1',
      fixVersion: '7.5.8',
      severity: 'Moderate',
      cve: 'GHSA-8qq5-xxxx',
      vulnerability: 'Hardlink Path Traversal',
      action: 'Upgrade to 7.5.8+',
    },
    {
      id: 'D-006',
      package: 'serialize-javascript',
      currentVersion: '6.0.0',
      fixVersion: '7.0.3',
      severity: 'Moderate',
      cve: 'GHSA-5c6j-xxxx',
      vulnerability: 'XSS via unsafe serialization',
      action: 'Upgrade to 7.0.3+',
    },
    {
      id: 'D-007',
      package: 'webpack',
      currentVersion: '5.101.2',
      fixVersion: 'Latest',
      severity: 'Low',
      cve: 'GHSA-8fgc-xxxx',
      vulnerability: 'SSRF',
      action: 'Upgrade to latest',
    },
    {
      id: 'D-008',
      package: 'brace-expansion',
      currentVersion: '1.1.11',
      fixVersion: '1.1.12',
      severity: 'Low',
      cve: 'GHSA-v6h7-xxxx',
      vulnerability: 'ReDoS',
      action: 'Upgrade to 1.1.12+',
    },
  ];
}

function countScaBuckets(deps: ScaDependencyRow[]): {
  Critical: number;
  High: number;
  Medium: number;
  Low: number;
  Warning: number;
} {
  const counts = { Critical: 0, High: 0, Medium: 0, Low: 0, Warning: 0 };
  for (const row of deps) {
    if (row.severity === 'High') counts.High += 1;
    else if (row.severity === 'Moderate') counts.Medium += 1;
    else counts.Low += 1;
  }
  return counts;
}

function buildScaObservations(repoName: string, deps: ScaDependencyRow[]): string[] {
  if (!deps.length) return ['No vulnerable dependencies detected in this scan.'];

  const observations: string[] = [];
  const high = deps.filter((d) => d.severity === 'High');
  const moderate = deps.filter((d) => d.severity === 'Moderate');
  const packages = new Set(deps.map((d) => d.package));

  if (high.length) {
    observations.push(
      `${high.length} high-severity vulnerable package${high.length === 1 ? '' : 's'} in ${repoName} require immediate upgrade or patching.`
    );
  }
  if (moderate.length) {
    observations.push(
      `${moderate.length} moderate-severity dependencies flagged with known CVEs — schedule remediation in the next sprint.`
    );
  }
  observations.push(
    `${deps.length} outdated or vulnerable dependencies identified across ${packages.size} package${packages.size === 1 ? '' : 's'}.`
  );

  const redos = deps.filter((d) => /redos/i.test(d.vulnerability));
  if (redos.length) {
    observations.push(
      `ReDoS (Regular Expression Denial of Service) vulnerabilities found in ${redos.length} package${redos.length === 1 ? '' : 's'}.`
    );
  }

  const pollution = deps.filter((d) => /prototype pollution/i.test(d.vulnerability));
  if (pollution.length) {
    observations.push('Prototype pollution risk identified — review object merge patterns in dependent code.');
  }

  return observations.slice(0, 6);
}

export function buildScaReportHtml(ctx: SecurityReportContext): string {
  const repoName = ctx.resource?.name ?? 'repository';
  const target =
    ctx.resource?.type === 'repository'
      ? `${ctx.resource.repoUrl ?? '—'}${ctx.resource.defaultBranch ? ` (${ctx.resource.defaultBranch})` : ''}`
      : ctx.resource?.targetUrl ?? '—';
  const generatedAt = formatTimestampIST(new Date().toISOString());
  const docTitle = buildReportDocumentTitle('sca', ctx.tool.name, repoName);

  const dependencies = ctx.scaDependencies ?? sampleScaDependencies(ctx.tool.id);
  const counts = countScaBuckets(dependencies);
  const total = dependencies.length;
  const criticalHigh = counts.Critical + counts.High;
  const lowInfo = counts.Low + counts.Warning;
  const observations = buildScaObservations(repoName, dependencies);

  const dependencyRows = dependencies
    .map(
      (row, index) => `
      <tr class="${index % 2 === 0 ? 'row-alt' : ''}">
        <td>${escapeHtml(row.id)}</td>
        <td class="text-left"><code>${escapeHtml(row.package)}</code></td>
        <td>${escapeHtml(row.currentVersion)}</td>
        <td>${escapeHtml(row.fixVersion)}</td>
        <td class="${scaSeverityClass(row.severity)}">${escapeHtml(row.severity)}</td>
        <td class="text-left">${escapeHtml(row.cve)}</td>
        <td class="text-left">${escapeHtml(row.vulnerability)}</td>
        <td class="text-left">${escapeHtml(row.action)}</td>
      </tr>`
    )
    .join('');

  const observationItems = observations.map((item) => `<li>${escapeHtml(item)}</li>`).join('');

  const header = buildReportHeaderHtml({
    categoryLabel: 'SCA',
    toolName: escapeHtml(ctx.tool.name),
    resourceName: escapeHtml(repoName),
    subtitle: categoryReportSubtitle('sca'),
    generatedAt: escapeHtml(generatedAt),
    targetLabel: 'Repository',
    targetValue: escapeHtml(target),
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(docTitle)}</title>
  <style>${reportPageStyles()}</style>
</head>
<body>
  <div class="page">
    ${header}
    <div class="report-body">
      <h2>Issue Summary</h2>
      <table class="summary-table">
        <thead>
          <tr>
            <th>Total Issues</th>
            <th>Critical / High</th>
            <th>Medium</th>
            <th>Low / Info</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="cell-total">${total}</td>
            <td class="cell-critical-high">${criticalHigh}</td>
            <td class="cell-medium">${counts.Medium}</td>
            <td class="cell-low-info">${lowInfo}</td>
          </tr>
        </tbody>
      </table>

      <h2>Issues by Repository</h2>
      <table>
        <thead>
          <tr>
            <th class="text-left">Repository</th>
            <th class="col-critical">Critical</th>
            <th class="col-high">High</th>
            <th>Medium</th>
            <th>Low</th>
            <th>Warning</th>
            <th>Tool</th>
          </tr>
        </thead>
        <tbody>
          <tr class="row-alt">
            <td class="text-left">${escapeHtml(repoName)}</td>
            <td class="col-critical">${counts.Critical}</td>
            <td class="col-high">${counts.High}</td>
            <td>${counts.Medium}</td>
            <td>${counts.Low}</td>
            <td>${counts.Warning}</td>
            <td>${escapeHtml(ctx.tool.name)}</td>
          </tr>
        </tbody>
      </table>

      <h3>Key Observations</h3>
      <div class="observations">
        <ul>${observationItems}</ul>
      </div>

      <h2>4.1 Vulnerable Dependencies</h2>
      <table class="sca-table detail-table">
        <thead>
          <tr>
            <th>ID</th>
            <th class="text-left">Package</th>
            <th>Current Ver.</th>
            <th>Fix Ver.</th>
            <th>Severity</th>
            <th class="text-left">CVE</th>
            <th class="text-left">Vulnerability</th>
            <th class="text-left">Action</th>
          </tr>
        </thead>
        <tbody>${dependencyRows || '<tr><td colspan="8" style="text-align:center;padding:24px;">No vulnerable dependencies</td></tr>'}</tbody>
      </table>
    </div>
    <p class="report-footer">SecureNexus Security · Generated by ${escapeHtml(ctx.tool.name)}</p>
  </div>
</body>
</html>`;
}

export function sampleFindings(toolId: string): Array<{
  severity: string;
  rule: string;
  location: string;
  message: string;
}> {
  const base = [
    {
      severity: 'High',
      rule: `${toolId}:hardcoded-secret`,
      location: 'src/config/settings.ts:42',
      message: 'Potential hard-coded credential detected in configuration module.',
    },
    {
      severity: 'Medium',
      rule: `${toolId}:outdated-dependency`,
      location: 'package-lock.json',
      message: 'Transitive dependency has a known CVE with a patched version available.',
    },
    {
      severity: 'Low',
      rule: `${toolId}:missing-security-header`,
      location: 'nginx.conf',
      message: 'Content-Security-Policy header is not configured.',
    },
  ];

  if (toolId === 'zap') {
    return [
      {
        severity: 'High',
        rule: 'zap:10021',
        location: '/api/login',
        message: 'X-Content-Type-Options header missing on authentication endpoint.',
      },
      {
        severity: 'Medium',
        rule: 'zap:90022',
        location: '/dashboard',
        message: 'Application does not set anti-clickjacking headers.',
      },
    ];
  }

  return base;
}

export function countFindingsBySeverity(findings: Array<{ severity: string }>): {
  high: number;
  medium: number;
  low: number;
} {
  let high = 0;
  let medium = 0;
  let low = 0;
  for (const row of findings) {
    const sev = row.severity.toLowerCase();
    if (sev === 'high' || sev === 'critical') high += 1;
    else if (sev === 'medium' || sev === 'moderate') medium += 1;
    else low += 1;
  }
  return { high, medium, low };
}

export function countScaDependenciesBySeverity(toolId: string): {
  high: number;
  medium: number;
  low: number;
} {
  return countFindingsBySeverity(sampleScaDependencies(toolId));
}

export function securityReportToPdfBuffer(ctx: SecurityReportContext): Promise<Buffer> {
  const findings =
    ctx.severityCounts && ctx.tool.id === 'semgrep'
      ? [
          {
            severity: 'Summary',
            rule: 'Semgrep live scan',
            location: '—',
            message: `${ctx.severityCounts.high} high · ${ctx.severityCounts.medium} medium · ${ctx.severityCounts.low} low findings. Open the HTML report for full details.`,
          },
        ]
      : sampleFindings(ctx.tool.id);
  return import('pdfkit').then(
    ({ default: PDFDocument }) =>
      new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 48, size: 'A4' });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        doc.fontSize(18).fillColor('#0f172a').text(ctx.title);
        doc.moveDown(0.4);
        doc.fontSize(10).fillColor('#64748b');
        doc.text(`Tool: ${ctx.tool.name}`);
        doc.text(`Generated: ${formatTimestampIST(new Date().toISOString())}`);
        doc.text(ctx.summary);
        doc.moveDown(0.8);

        doc.fontSize(11).fillColor('#0f172a').text('Findings', { underline: true });
        doc.moveDown(0.4);

        findings.forEach((row, index) => {
          doc.fontSize(9).fillColor('#334155');
          doc.text(`${index + 1}. [${row.severity}] ${row.rule}`);
          doc.fontSize(8).fillColor('#64748b');
          doc.text(`   ${row.location} — ${row.message}`);
          doc.moveDown(0.35);
        });

        doc.moveDown(0.5);
        doc.fontSize(8).fillColor('#94a3b8').text('SecureNexus Security Report');
        doc.end();
      })
  );
}
