import { formatTimestampIST } from '@/lib/utils';
import {
  buildReportHeaderHtml,
  categoryReportLabel,
  reportPageStyles,
} from '@/lib/security-report-html';
import type { SecurityResourceView } from '@/lib/security-service';

export interface SnykFindingRow {
  severity: 'Critical' | 'High' | 'Medium' | 'Low';
  rule: string;
  title: string;
  location: string;
  message: string;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function severityBadgeClass(severity: SnykFindingRow['severity']): string {
  switch (severity) {
    case 'Critical':
      return 'sev-critical';
    case 'High':
      return 'sev-high';
    case 'Medium':
      return 'sev-medium';
    default:
      return 'sev-low';
  }
}

export function buildSnykReportHtml(input: {
  resource: SecurityResourceView;
  toolName: string;
  title: string;
  summary: string;
  scanKind: string;
  findings: SnykFindingRow[];
  snykVersion: string;
}): string {
  const { resource, toolName, title, summary, findings } = input;
  const generatedAt = formatTimestampIST(new Date().toISOString());
  const targetLabel = resource.type === 'target_url' ? 'URL Target' : 'Repository';
  const targetValue =
    resource.type === 'repository'
      ? `${resource.repoUrl ?? '—'}${resource.defaultBranch ? ` (${resource.defaultBranch})` : ''}`
      : resource.targetUrl ?? '—';

  const order: SnykFindingRow['severity'][] = ['Critical', 'High', 'Medium', 'Low'];
  const counts = {
    Critical: findings.filter((f) => f.severity === 'Critical').length,
    High: findings.filter((f) => f.severity === 'High').length,
    Medium: findings.filter((f) => f.severity === 'Medium').length,
    Low: findings.filter((f) => f.severity === 'Low').length,
  };

  const sorted = [...findings].sort(
    (a, b) => order.indexOf(a.severity) - order.indexOf(b.severity)
  );

  const rows = sorted.length
    ? sorted
        .map(
          (row) => `
      <tr>
        <td><span class="badge ${severityBadgeClass(row.severity)}">${escapeHtml(row.severity)}</span></td>
        <td class="col-vulnerability">${escapeHtml(row.title)}</td>
        <td class="col-location"><code>${escapeHtml(row.location)}</code></td>
        <td>${escapeHtml(row.message)}</td>
      </tr>`
        )
        .join('')
    : `<tr><td colspan="4" style="text-align:center;">No issues detected in this scan.</td></tr>`;

  const header = buildReportHeaderHtml({
    categoryLabel: categoryReportLabel('sca'),
    toolName: escapeHtml(toolName),
    resourceName: escapeHtml(resource.name),
    subtitle: `${escapeHtml(input.scanKind)} · powered by Snyk`,
    generatedAt: escapeHtml(generatedAt),
    targetLabel,
    targetValue: escapeHtml(targetValue),
    extraMeta: { label: 'Snyk CLI', value: escapeHtml(input.snykVersion) },
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
  <style>${reportPageStyles()}</style>
</head>
<body>
  <div class="page">
    ${header}
    <div class="report-body">
      <div class="summary-box">${escapeHtml(summary)}</div>
      <h2>Severity summary</h2>
      <table class="summary-table">
        <thead>
          <tr>
            <th class="cell-total">Total</th>
            <th class="cell-critical-high">Critical</th>
            <th class="cell-critical-high">High</th>
            <th class="cell-medium">Medium</th>
            <th class="cell-low-info">Low</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="cell-total">${findings.length}</td>
            <td class="cell-critical-high">${counts.Critical}</td>
            <td class="cell-critical-high">${counts.High}</td>
            <td class="cell-medium">${counts.Medium}</td>
            <td class="cell-low-info">${counts.Low}</td>
          </tr>
        </tbody>
      </table>
      <h2>Findings</h2>
      <table class="detail-table findings-table">
        <thead>
          <tr>
            <th>Severity</th>
            <th class="col-vulnerability">Issue</th>
            <th class="col-location">Location</th>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
    <p class="report-footer">SecureNexus Security · Generated by ${escapeHtml(toolName)}</p>
  </div>
</body>
</html>`;
}
